spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://localhost:8081
          predicates:
            - Path=/students
        - id: course-service
          uri: http://localhost:8083
          predicates:
            - Path=/courses
server:
  port: 8181

app:
  eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
